version: 2.1

orbs:
  node: circleci/node@1.1.2

jobs:
  build:
    executor:
      name: node/default
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - node/with-cache:
          cache-key    : yarn.lock
          cache-version: v1
          steps:
            - run:
                name   : Install dependencies
                command: yarn install
            - run:
                name   : Build project
                command: yarn build
            - run:
                name   : Run all Tests
                command: yarn test
            - store_test_results:
                path: /tmp/test-reports

workflows:
  main:
    jobs:
      - build
