version: 2.1

orbs:
  node: circleci/node@1.1.2

jobs:
  build:
    executor:
      name: node
    steps:
      - checkout
      - node/with-cache:
          cache-key    : yarn.lock
          cache-version: v1
          steps:
            - run:
                name   : Install dependencies
                command: yarn install
            - run:
                name   : Build project
                command: yarn build
  test:
    executor:
      name: node
    steps:
      - run:
          name   : Run all Tests
          command: yarn test

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
