name: fetch-urls

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Get Yarn Cache Dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        run: yarn install
      - name: Run Script (fetch-urls)
        run: yarn fetch-urls
      - name: Run Tests
        run: yarn test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: create-pull-request/fetch-urls
          delete-branch: true
          title: Changes by fetch-urls workflow
